name: Publish site into main (for Pages from branch)

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write   # 需要能 push 回 main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # GitHub Pages 的來源資料夾：
      # - 用 /docs：PAGES_DIR=docs（建議）
      # - 用根目錄：PAGES_DIR='.'
      PAGES_DIR: docs

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Download latest release ZIP(s)
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*.zip'          # 不固定檔名：抓所有 zip 資產
          out-file-path: download
          extract: true              # 自動解壓到 download/

      - name: Collect site files (flatten)
        run: |
          set -euo pipefail
          mkdir -p site
          rm -f download/*.zip || true

          # 若只有一個最外層資料夾，提升其內容；否則把所有解壓內容搬到 site/
          if [ "$(find download -mindepth 1 -maxdepth 1 -type d | wc -l)" -eq "1" ]; then
            d="$(find download -mindepth 1 -maxdepth 1 -type d)"
            shopt -s dotglob && mv "$d"/* site/ || true
          else
            shopt -s dotglob && mv download/* site/ || true
          fi

          # 基本健檢：至少要有首頁
          test -f site/index.html || { echo "index.html not found"; exit 1; }

      - name: Copy into ${{ env.PAGES_DIR }}
        run: |
          set -euo pipefail
          mkdir -p "${PAGES_DIR}"
          # 同步站檔到 PAGES_DIR；排除 repo/CI 自身的檔案
          rsync -av --delete \
            --exclude ".git" \
            --exclude ".github" \
            site/ "${PAGES_DIR}/"

      - name: Commit & push to main (Pages dir only)
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 只加入 Pages 來源資料夾，避免把 download/、site/ 推上去
          git add -A "${PAGES_DIR}"

          # 若 staged 沒變化就跳過
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          msg="Update Pages content from release ${GITHUB_REF_NAME:-manual}"
          git commit -m "$msg"
          git push
